server:
  port: 8082
# Kafka props
spring:
  kafka:
    producer: 
      bootstrap-servers: 
        localhost:9092
      key.deserializer:
        org.apache.kakfa.common.serialization.StringSerializer
      value.deserializer: 
        org.apache.kafka.common.serialization.StringSerializer

